# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel

sudo: false
cache: packages

warnings_are_errors: false

env:
  - R_REMOTES_UPGRADE="always"

before_install:
  - mkdir -p ~/.R
  - echo -e 'MAKEFLAGS = -j2' > ~/.R/Makevars
  - echo 'options(Ncpus = 2)' > ~/.Rprofile
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install(dependencies=TRUE)'

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

r_packages:
  - covr
  - BiocManager

after_success:
  - Rscript -e 'library(covr); codecov()'
  
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch:
      - master
      - pkgdown
