# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel

sudo: false
cache: packages

warnings_are_errors: false

before_install:
    - Rscript -e 'install.packages("devtools")'
    - Rscript -e 'devtools::install(dependencies = c("Depends", "Imports", "Suggests", "Enhances"))'

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

bioc_packages:
  - BiocInstaller

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
